language: node_js

branches:
  only:
    - master

node_js:
  - 19

jobs:
  include:
    - stage: build-and-deploy
      script:
        - npx semantic-release

stages:
  - name: build-and-deploy
    if: branch = master AND type = push

